### ISSUE TITLE
VScode doesn't launch when apply monkey patch

### ISSUE THREAD

**Issue by DarkHeros09** [iocave/customize-ui#157]
Hi 

VSCode stopped working after updating to v1.74

```Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

**Comment by knopp** [comment]
Sadly that's expected. 

https://github.com/iocave/customize-ui/issues/157

**Comment by DarkHeros09** [comment]
> Sadly that's expected.
> 
> #157

why?

**Comment by mazwrld** [comment]
Very very sad news 😭😭... Just had to downgrade VS code. I will keep using this version(1.73) till the day I die

**Comment by knopp** [comment]
My bad, for some reason I linked wrong issue:

https://github.com/iocave/customize-ui/issues/156

**Comment by ekwoka** [comment]
NOOOOOOO

**Comment by ekwoka** [comment]
@phonethawhtet it's on Microsoft to fix VScode.

**Comment by postylem** [comment]
So... how can one get VSCode to launch again?  I re-enabled Customize UI today after having it turned off for a while, and now I can't open VSCode at all. Help!

I tried running from command line, without extensions, and still, I get no windows opening.

```bash
code-insiders --verbose --disable-extensions
```

<details>
<summary>
prints:
</summary>
<pre><code>                
Loading monkey-patch
(node:78991) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'crypto')
    at w (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:25:26848)
    at t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:25:36287)
    at get mainIPCHandle (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:33:1785)
    at M.g.<computed> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:3:20488)
    at Oe.c (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:86:6508)
    at Oe.b (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:86:4951)
    at Oe.a (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:86:3957)
    at Oe.main (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:86:3802)
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.js:87:1717)
    at s._safeInvokeFunction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:1337)
    at s._invokeFactory (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:1522)
    at s.complete (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:1801)
    at s._onModuleComplete (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:6:1112)
    at s._onModuleComplete (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:6:1358)
    at s._resolve (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:6:510)
    at s.defineModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:6066)
    at n (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:10527)
    at Object.R (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:6:6036)
    at s._safeInvokeFunction (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:1337)
    at s._invokeFactory (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:1522)
    at s.complete (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:1801)
    at s._onModuleComplete (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:6:1112)
    at s._onModuleComplete (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:6:1358)
    at s._resolve (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:6:510)
    at s.defineModule (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:5:6066)
    at y (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:6:1825)
    at h (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:2554)
    at Object.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-main/main.nls.js:3:61)
    at e._createAndEvalScript (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:2598)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:4:2237
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/bootstrap-amd.js:82:14
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:78991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
</code></pre>
</details>

--------------

EDIT: Oops should have read some more before posting.

I see now that this extension is just not going to work anymore.

Just in case this is helpful for anyone else:

I re-downloaded the application, and the issue was fixed, but if I re-enable Monkey Patch, it happens again, the application won't launch, as above.

Version info:

`code-insiders --list-extensions --show-versions`
```
...
iocave.customize-ui@0.1.65
iocave.monkey-patch@0.1.23
```
`code-insiders --version`
```                        
1.77.0-insider
06ce7933733b1ab05e410e46a6a622dfffb31927
arm64
```
