### ISSUE TITLE
Bug with "workbench.sideBar.location": "right"

### ISSUE THREAD

**Issue by melMass** [iocave/customize-ui#34]
Hi,

Thanks for this extension, I love the tweaks it provides.
I have a bug on Mac using `"workbench.sideBar.location": "right"`, when I resize the sidebar it opens the search panel, and also extending the search panel results in a strange result:

![image](https://user-images.githubusercontent.com/7041726/75810853-a6e3b680-5d8b-11ea-872f-4838924110d7.png)

**Comment by knopp** [comment]
I don't seem to be able to reproduce this, which vscode version do you have installed?

**Comment by melMass** [comment]
Latest insiders under Mojave. Might be due to an other mix of settings I'll check but I think it was using all the settings from the readme

**Comment by knopp** [comment]
Can you maybe post the relevant parts of your settings.json here? I'm on latest insiders on catalina (that shouldn't make difference) and I can't seem to be able to reproduce the issue.

**Comment by melMass** [comment]
I found the settings that don't go well together:

If you have both :
```json
{
"workbench.panel.defaultLocation": "right",
"workbench.sideBar.location": "right"
}
```

The error occurs, I don't care about having both to the right, I moved the panel (search|terminal|problems etc...) to the left for now and the issue is not there anymore.

Can you reproduce it now ?

**Comment by melMass** [comment]
Maybe there is something more... I'll investigate:

![image](https://user-images.githubusercontent.com/7041726/75873185-c7edeb00-5e0f-11ea-8d37-57f5ea4ea36e.png)

**Comment by melMass** [comment]
I think something is wrong with monkey patch activation, it requires me to manually close the window, then it initiates the restart but I feel something might be off there.
Can I provide more info to debug this? Every time I open a new window now I have the result from previous post :(

**Comment by knopp** [comment]
That's normal. There's currently no way to trigger vscode restart, so you need to close the window manually in order for restart to happen.

You can try to go to ~/Library/Applicaiton Support/Code - Insiders and rename all folders except User (that's where your settings are).  Maybe there's some old code cached.

I can't reproduce this with your settings. 

```
{
"workbench.panel.defaultLocation": "right",
"workbench.sideBar.location": "right"
}
```
work fine for me (except sidebar size on show/hide which will be fixed soon)

**Comment by melMass** [comment]
I tried again with the same results

I tried to debug it but I have no clue how to properly do it. If I have the time I'll dig deeper, but in the meantime, those errors might shine a light on the issue I have?

```ruby
  ERR Cannot read property 'layout' of undefined: TypeError: Cannot read property 'layout' of undefined
    at V.layout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6117:515)
    at CustomizeTitleBar.update (file:///Users/imac/Library/Application Support/Code - Insiders/User/globalStorage/iocave.customize-ui/modules/title-bar.js:316:33)
    at V.<anonymous> (file:///Users/imac/Library/Application Support/Code - Insiders/User/globalStorage/iocave.customize-ui/modules/title-bar.js:183:26)
    at V.where.<computed> (file:///Users/imac/Library/Application Support/Code - Insiders/User/globalStorage/iocave.customize-ui/modules/utils.js:10:30)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6102:377
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at e.doHandleActiveEditorChangeEvent (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5834:358)
    at e.handleActiveEditorChange (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5834:156)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5833:258
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at e.doSetGroupActive (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6062:1001)
    at Object.fromJSON (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6067:1005)
    at v._deserializeNode (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:527:528)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:527:378
    at Array.map (<anonymous>)
    at v._deserializeNode (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:527:359)
    at v._deserialize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:527:264)
    at Function.deserialize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:527:198)
    at Function.deserialize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:536:752)
    at e.doCreateGridControlWithState (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6067:890)
    at e.doCreateGridControlWithPreviousState (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6067:478)
    at e.doCreateGridControl (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6066:959)
    at e.createContentArea (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6066:192)
    at e.create (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2889:218)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6192:97
    at Array.forEach (<anonymous>)
    at V.renderWorkbench (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6192:4)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6188:771
    at _InstantiationService.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1591:375)
    at V.startup (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6188:483)
    at q.open (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7145:911)
```

```ruby
ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

**Comment by knopp** [comment]
Hi,

this seems to be a problem with today's insider. I am able to reproduce the problem locally.

**Comment by melMass** [comment]
Ahaha I'm cursed

**Comment by knopp** [comment]
I've published 0.1.35. It fixes the exception with latest insiders, as well as problem of activity bar showing when sidebar is hidden. But the exception was not related to any other issue in this thread (reported earlier) which I still can't reproduce.

**Comment by knopp** [comment]
Can you please post screenshot of your normal vscode workspace layout (without customize UI). Maybe I'll be able to reproduce the problem/

**Comment by melMass** [comment]
There you go, at the end of the video I'm using shortcuts to toggle the debug console and the sidebar
![customise_ui](https://user-images.githubusercontent.com/7041726/79806661-39a2d980-8369-11ea-8d5a-e25a45c906eb.gif)

**Comment by knopp** [comment]
Is your panel location left? This is not currently supported in customize UI. It's relatively new and I it's might be quite a lot of work to get this working with inline titlebar. Only supported panel locations are right and bottom. Sidebar can be both right and left.

Does it work when you do View -> Appearance -> Move panel right/bottom ?

**Comment by melMass** [comment]
That's it I think! I was moving the panel around but each time I opened a new project it would result in that behavior, the reason ? I had 
```json
{
"workbench.panel.defaultLocation": "left"
}
```
Replaced with:
```json
{
"workbench.panel.defaultLocation": "bottom"
}
```

I think maybe you should add a disclaimer in the Readme about clashing settings.

Thanks for the quick replies I love my new UI ❤️

**Comment by melMass** [comment]
I'm closing the issue as I've been using it for a few days without any issues.
