### ISSUE TITLE
Debug panel blank when running in debug mode

### ISSUE THREAD

**Issue by Cammisuli** [iocave/customize-ui#64]
When starting a debug session, the debug terminal becomes blank, showing none of the panels:
![image](https://user-images.githubusercontent.com/4332460/92515736-1080c980-f1e2-11ea-849d-a604732d8d29.png)

Error that shows up in the console is this:
```
ERR Cannot read property 'view' of undefined: TypeError: Cannot read property 'view' of undefined
    at W.replacement (file:///Users/jon/Library/Application Support/Code/User/globalStorage/iocave.customize-ui/modules/fonts.js:154:32)
    at W.where.<computed> (file:///Users/jon/Library/Application Support/Code/User/globalStorage/iocave.customize-ui/modules/utils.js:10:30)
    at W.render (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1079:57)
    at W.render (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6547:154)
    at R.onDidAddViewDescriptors (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6567:163)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6562:142
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at S.onDidChangeContext (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5943:682)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5936:776
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:91:482
    at t.PauseableEmitter.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at t.PauseableEmitter.resume (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:96:349)
    at _.bufferChangeEvents (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1860:587)
    at G.onStateChange (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6785:456)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6784:64
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:801)
    at t.ViewModel.setFocus (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3211:614)
    at G.focusStackFrame (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6796:837)
    at G.launchOrAttachToSession (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6791:604)
    at async G.doCreateSession (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6790:323)
    at async G.startDebugging (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6787:924)
```

Which looks to originate from here:
https://github.com/iocave/customize-ui/blob/f893cb23658e79ee967ae639b18291396d289da9/modules/fonts.js#L154

```
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 20.0.0

Customise UI: v0.1.47

```

**Comment by knopp** [comment]
Thank you for the report. I can't seem to be able to reproduce this with current insiders. What kind of debug configuration is this?

**Comment by Cammisuli** [comment]
Using the `Javascript Debug Terminal`
![image](https://user-images.githubusercontent.com/4332460/92521355-1a5afa80-f1eb-11ea-8719-c250c4ea51a5.png)

**Comment by knopp** [comment]
It seems to have been caused by the loaded scripts view. I pushed 0.1.48 update, it should be live in few minutes. Please let me know if it resolves your problem.

**Comment by Cammisuli** [comment]
Awesome! Looks good now! 😄
